#pragma once

#define VIAL_KEYBOARD_UID {0xB9, 0x8E, 0x31, 0x54, 0xBE, 0xAE, 0x9A, 0x72}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define VIAL_TAP_DANCE_ENTRIES 10
#define VIAL_COMBO_ENTRIES 15
#define VIAL_KEY_OVERRIDE_ENTRIES 10
